name: Examples

on: [push, pull_request]

# on:
#   push:
#     branches:
#       - master

defaults:
  run:
    shell: bash

jobs:
  browserify:
    runs-on: ubuntu-20.04
    container:
      image: cypress/base:17.3.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache NPM modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm
      - name: Cache Cypress binaries
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: cypress
      # In lack of native support, https://github.com/actions/checkout/issues/172.
      - name: Make checkout sparse
        run: |
          shopt -s extglob
          rm -rf examples/!(browserify)
          rm -rf !(examples)
      - name: Install NPM modules
        working-directory: examples/browserify
        run: npm install --legacy-peer-deps
      - name: Run Cypress
        working-directory: examples/browserify
        run: npx cypress run

  webpack:
    runs-on: ubuntu-20.04
    container:
      image: cypress/base:17.3.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache NPM modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm
      - name: Cache Cypress binaries
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: cypress
      # In lack of native support, https://github.com/actions/checkout/issues/172.
      - name: Make checkout sparse
        run: |
          shopt -s extglob
          rm -rf examples/!(webpack)
          rm -rf !(examples)
      - name: Install NPM modules
        working-directory: examples/webpack
        run: npm install --legacy-peer-deps
      - name: Run Cypress
        working-directory: examples/webpack
        run: npx cypress run

  esbuild:
    runs-on: ubuntu-20.04
    container:
      image: cypress/base:17.3.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache NPM modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm
      - name: Cache Cypress binaries
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: cypress
      # In lack of native support, https://github.com/actions/checkout/issues/172.
      - name: Make checkout sparse
        run: |
          shopt -s extglob
          rm -rf examples/!(esbuild)
          rm -rf !(examples)
      - name: Install NPM modules
        working-directory: examples/esbuild
        run: npm install --legacy-peer-deps
      - name: Run Cypress
        working-directory: examples/esbuild
        run: npx cypress run
